name:                flhaskell
version:             0.1.0.0
github:              "cbare/flhaskell"
license:             BSD3
author:              "J. Christopher Bare"
maintainer:          "christopherbare@gmail.com"
copyright:           "J. Christopher Bare"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cbare/flhaskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  flhaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flhaskell
    - parsec >= 3.1.14.0
    - QuickCheck


tests:
  flhaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flhaskell
    - parsec >= 3.1.14.0
    - quickcheck
